spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pingfen?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 111111
logging:
  config: classpath:logger-config.xml
  level:
    cn.qianshu.pingfen: info
    cn.qianshu.pingfen.dao: debug
  file: 
    path: D:/SuperMapDataLogs/mylogs/mylogs.log